# Generated by Django 3.1.3 on 2020-11-23 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Properties',
            new_name='Propertie',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
