# Generated by Django 3.1.3 on 2020-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201123_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertie',
            name='id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='propertie',
            name='street_address',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
