# Generated by Django 3.1.3 on 2020-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201123_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertie',
            name='route',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
