# Generated by Django 3.1.3 on 2020-11-23 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_propertie_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertie',
            name='day',
        ),
    ]
