# Generated by Django 3.1.3 on 2020-11-23 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_propertie_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='assigned_Route',
            new_name='assigned_route',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
