# Generated by Django 3.1.3 on 2020-11-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20201123_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Propertie',
            new_name='Property',
        ),
    ]
